### ISSUE TITLE
"Edit wallpaper" doesn't work

### ISSUE THREAD

**Issue by nico-onmap** [FriendSoftwareLabs/friendup#24]
When right-clicking & choosing `edit wallpaper`, I am getting an empty window. In the console I have this error:

```
VM2410:1 Uncaught SyntaxError: Unexpected token i in JSON at position 2
    at JSON.parse (<anonymous>)
    at Module.m.onExecuted (module?module=system&sessionid=fbe3436…&command=launch&app=Wallpape…:46)
    at receiveEvent (api.js:1157)
```

**Comment by titlestad** [comment]
Can you give us browser, version and OS?

**Comment by nico-onmap** [comment]
Windows 10 64 bit (Insiders build 16237)
Chrome Version 59.0.3071.115 (64 bit)

**Comment by titlestad** [comment]
Can't reproduce it on Chrome Version 55.0.x on Linux with the latest code. Anyone able to reproduce on a Windows computer with this version?

**Comment by stefkosdev** [comment]
Works here:
Windows 10 Pro, Chrome: Wersja 59.0.3071.115 (Oficjalna wersja) (64-bitowa)

**Comment by titlestad** [comment]
Hmm, could you post the contents of the response?

**Comment by nico-onmap** [comment]
It's crashing here:

```
	// Lets load our main settings file
	var m = new Module( 'system' );
	m.onExecuted = function( e, d )
	{
		if( e == 'ok' )
		{
			// Copy settings in
			if( !Application.settings ) Application.settings = {};
			var setar = JSON.parse( d );
			for( var a in setar )
				Application.settings[a] = setar[a];
		}
```

it's trying to parse `d == "fail"` which is not a valid json.

Note that I am using this url to access friendup: [friendup](https://beta.openfriendup.net/webclient/index.html)

**Comment by titlestad** [comment]
Aha, fix coming up :)

**Comment by titlestad** [comment]
See if that commit did the trick..

**Comment by nico-onmap** [comment]
No change, same crash.

**Comment by titlestad** [comment]
Will try on a blank instance. Anyone else experience this bug?

**Comment by titlestad** [comment]
Oi, wrong button! My bad! :)

**Comment by warpdesign** [comment]
Any progress on that bug?

**Comment by titlestad** [comment]
I think this has been fixed in 1.1. It will be available in a few days.

**Comment by warpdesign** [comment]
@titlestad No: I just tried and the bug is still present (using [beta version](https://beta.openfriendup.net/)).

**Comment by titlestad** [comment]
That's weird. Ok, I have added a try catch and made sure the "d" variable is set to null on fail. Let's test it when we update the beta in a few days.

**Comment by titlestad** [comment]
Fantastic :-)
